/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReadRouteImport } from './routes/read'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WriteRouteImport } from './routes/write'
import { Route as WriteDestinationRouteImport } from './routes/write-destination'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth.complete-profile'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as PagesPageIdRouteImport } from './routes/pages.$pageId'
import { Route as TShortIdRouteImport } from './routes/t.$shortId'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as TagsTagIdRouteImport } from './routes/tags.$tagId'
import { Route as TagsAddRouteImport } from './routes/tags.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteDestinationRoute = WriteDestinationRouteImport.update({
  id: '/write-destination',
  path: '/write-destination',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const TShortIdRoute = TShortIdRouteImport.update({
  id: '/t/$shortId',
  path: '/t/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TagsRoute,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/$tagId',
  path: '/$tagId',
  getParentRoute: () => TagsRoute,
} as any)
const TagsAddRoute = TagsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => TagsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/read': typeof ReadRoute
  '/tags': typeof TagsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/write': typeof WriteRoute
  '/write-destination': typeof WriteDestinationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/p/$slug': typeof PSlugRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/t/$shortId': typeof TShortIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/add': typeof TagsAddRoute
  '/pages/': typeof PagesIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/read': typeof ReadRoute
  '/tools': typeof ToolsRoute
  '/write': typeof WriteRoute
  '/write-destination': typeof WriteDestinationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/p/$slug': typeof PSlugRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/t/$shortId': typeof TShortIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/add': typeof TagsAddRoute
  '/pages': typeof PagesIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/read': typeof ReadRoute
  '/tags': typeof TagsRouteWithChildren
  '/tools': typeof ToolsRoute
  '/write': typeof WriteRoute
  '/write-destination': typeof WriteDestinationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/p/$slug': typeof PSlugRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/t/$shortId': typeof TShortIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tags/add': typeof TagsAddRoute
  '/pages/': typeof PagesIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/diagnostics'
    | '/home'
    | '/profile'
    | '/read'
    | '/tags'
    | '/tools'
    | '/write'
    | '/write-destination'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/p/$slug'
    | '/pages/$pageId'
    | '/t/$shortId'
    | '/tags/$tagId'
    | '/tags/add'
    | '/pages/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/diagnostics'
    | '/home'
    | '/profile'
    | '/read'
    | '/tools'
    | '/write'
    | '/write-destination'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/p/$slug'
    | '/pages/$pageId'
    | '/t/$shortId'
    | '/tags/$tagId'
    | '/tags/add'
    | '/pages'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/diagnostics'
    | '/home'
    | '/profile'
    | '/read'
    | '/tags'
    | '/tools'
    | '/write'
    | '/write-destination'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/p/$slug'
    | '/pages/$pageId'
    | '/t/$shortId'
    | '/tags/$tagId'
    | '/tags/add'
    | '/pages/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  ReadRoute: typeof ReadRoute
  TagsRoute: typeof TagsRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  WriteRoute: typeof WriteRoute
  WriteDestinationRoute: typeof WriteDestinationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  PSlugRoute: typeof PSlugRoute
  PagesPageIdRoute: typeof PagesPageIdRoute
  TShortIdRoute: typeof TShortIdRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write-destination': {
      id: '/write-destination'
      path: '/write-destination'
      fullPath: '/write-destination'
      preLoaderRoute: typeof WriteDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$shortId': {
      id: '/t/$shortId'
      path: '/t/$shortId'
      fullPath: '/t/$shortId'
      preLoaderRoute: typeof TShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof TagsRoute
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof TagsRoute
    }
    '/tags/add': {
      id: '/tags/add'
      path: '/add'
      fullPath: '/tags/add'
      preLoaderRoute: typeof TagsAddRouteImport
      parentRoute: typeof TagsRoute
    }
  }
}

interface TagsRouteChildren {
  TagsTagIdRoute: typeof TagsTagIdRoute
  TagsAddRoute: typeof TagsAddRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagIdRoute: TagsTagIdRoute,
  TagsAddRoute: TagsAddRoute,
  TagsIndexRoute: TagsIndexRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  ReadRoute: ReadRoute,
  TagsRoute: TagsRouteWithChildren,
  ToolsRoute: ToolsRoute,
  WriteRoute: WriteRoute,
  WriteDestinationRoute: WriteDestinationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  PSlugRoute: PSlugRoute,
  PagesPageIdRoute: PagesPageIdRoute,
  TShortIdRoute: TShortIdRoute,
  PagesIndexRoute: PagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
